/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['body[_ngcontent-%COMP%] {\r\n    font-size: 20px;\r\n}\r\n.link1[_ngcontent-%COMP%] {\r\n    color:red;\r\n}\r\n.link[_ngcontent-%COMP%] {\r\n    color:blue;\r\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvc3BpbnN0YWxsZXIvRGVza3RvcC9hbmd1bGFyNGxhenkvc3JjL21haW4vbWFpbi1hcHAuY29tcG9uZW50LnNjc3Muc2hpbS5uZ3N0eWxlLnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovVXNlcnMvc3BpbnN0YWxsZXIvRGVza3RvcC9hbmd1bGFyNGxhenkvc3JjL21haW4vbWFpbi1hcHAuY29tcG9uZW50LnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
